name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Cache Fonts
        id: cache-fonts
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: fonts
          key: fonts

      - name: Fetch Fonts
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          mkdir fonts
          wget -O font.eot https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.eot
          wget -O font.woff2 https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.woff2
          wget -O font.woff https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.woff
          wget -O font.ttf https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.ttf
          wget -O font.svg https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.svg

      - name: Add Fonts to Output Dir
        run: cp fonts/* out/
        
      - name: Prepare GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
        
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'out/'

      - name: Deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
