name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Output Directory
        run: mkdir out

      - name: Cache Fonts
        id: cache-fonts
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: fonts
          key: fonts

      - name: Generate Annunciators
        run: |
          python3 -m venv venv/
          venv/bin/pip install -r requirements.txt
          venv/bin/python3 gen_annunciators.py

      - name: Fetch Fonts
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          mkdir fonts
          wget -O fonts/font.eot https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.eot
          wget -O fonts/font.woff2 https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.woff2
          wget -O fonts/font.woff https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.woff
          wget -O fonts/font.ttf https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.ttf
          wget -O fonts/font.svg https://db.onlinewebfonts.com/t/cc0c83f1e7a5a34cf6985d861f0b2e1c.svg

      - name: Add Fonts to Output Dir
        run: cp fonts/* out/
        
      - name: Prepare GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
        
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'out/'

      - name: Deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
